// Tests for cv::PointTracker (cv.jit.track: pyramidal Lucas-Kanade tracking of an explicit,
// persistent point set) and cv::GoodFeatures (cv.jit.features: Shi-Tomasi
// goodFeaturesToTrack), plus the GoodFeatures -> PointTracker chain, which is what the
// cv.jit.features2track abstraction does.
//
// ---------------------------------------------------------------------------------------
// HOW THE EXPECTATIONS ARE DERIVED
// ---------------------------------------------------------------------------------------
//
// TRACKING. Every tracking frame is generated by evaluating a smooth analytic texture
// `tex(u, v)` at `(x - tx, y - ty)`. The image is therefore an EXACT translation of the
// reference frame by (tx, ty) pixels, so the ground-truth position of a point seeded at
// (px, py) after a translation of (tx, ty) is exactly (px + tx, py + ty) -- no estimation,
// no tolerance beyond the tracker's own convergence and the 8-bit quantisation of the
// frames. That is what lets these tests assert positions to a twentieth of a pixel.
//
// The texture is a sum of four sinusoids with mutually incommensurate 2D frequencies:
// locally unique (so the LK match has a single minimum), band-limited well below Nyquist
// (so the pyramid's 2x2 box decimation does not alias) and non-degenerate in both
// directions (so the structure tensor is well conditioned and the aperture problem does not
// bite). Amplitude 85 around 128 keeps the frames inside [43, 213], leaving room to add a
// +-20 modulation without clipping.
//
// THE POINT OF THE ACCUMULATION TEST. cv::OpticalFlowLK reports a per-frame displacement on
// a grid that is regenerated every frame; this object carries the points across frames. So
// the load-bearing assertion is the TOTAL displacement after N frames (5 frames of (3,2) =
// (15,10)), which an object reporting instantaneous flow could never produce, and which
// would come out as (3,2) if the seeds were re-applied every frame.
//
// SHI-TOMASI. The response is the minimum eigenvalue of the structure tensor, which is
// QUADRATIC in the image gradient, so two otherwise identical corners whose contrasts are
// in ratio r have responses in ratio r^2. The scene below has one 12x12 square of grey 200
// and one of grey 126 on black: 126/200 = 0.63, so the weak square's response must be
// 0.63^2 = 0.3969 of the strong one. `Quality` is a RELATIVE level, so the weak corners
// survive quality 0.3 and are cut at quality 0.5 -- this is the difference between this
// object and cv::FastCorners, whose threshold is absolute.
//
// SUB-PIXEL. The refinement scene is a square rendered with exact area-coverage
// antialiasing over [20.3, 44.3]^2 in continuous coordinates, where pixel i covers
// [i - 0.5, i + 0.5]. The true corner is therefore at (20.3, 20.3) and the detector, which
// only reports integer maxima, cannot do better than 0.3 px away; `Precision` must land
// strictly closer and strictly off the integer grid.
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include "TestImage.hpp"

#include <CV/Cpu/GoodFeatures.hpp>
#include <CV/Cpu/PointTracker.hpp>

#include <algorithm>
#include <cmath>

using Catch::Approx;
using namespace cvtest;

namespace
{
constexpr int kW = 128;
constexpr int kH = 128;

// Band-limited, locally unique analytic texture (see the header comment).
float tex(float u, float v)
{
  float s = 0.f;
  s += 0.45f * std::sin(0.16f * u + 0.09f * v + 0.7f);
  s += 0.30f * std::sin(0.07f * u - 0.19f * v + 2.1f);
  s += 0.25f * std::sin(0.21f * u + 0.05f * v + 4.2f);
  s += 0.20f * std::sin(0.06f * u + 0.17f * v + 1.3f);
  return s;
}

// The texture translated by (tx, ty) pixels. `mod` adds +mod to even columns and -mod to
// odd ones: a 2-pixel-period pattern that is present in one frame only, which the tracker
// cannot absorb into a displacement and which therefore shows up in the error output.
Image frame(float tx, float ty, int mod = 0, int W = kW, int H = kH)
{
  Image img(W, H, 0);
  for(int y = 0; y < H; ++y)
    for(int x = 0; x < W; ++x)
    {
      float v = 128.f + 85.f * tex(x - tx, y - ty);
      if(mod != 0)
        v += (x & 1) ? static_cast<float>(mod) : -static_cast<float>(mod);
      v = std::clamp(v, 0.f, 255.f);
      img.setGray(x, y, static_cast<std::uint8_t>(std::lround(v)));
    }
  return img;
}

// Multi-scale texture for the pyramid test: a fine grating (wavelength 8 px, annihilated by
// the 2x2 box decimation at level 2) riding on a coarse component (wavelength ~120 px).
// At full resolution the fine grating dominates the gradient, so a single-level LK is
// trapped within ~2 px; the coarse component only becomes visible after decimation, which
// is exactly what a pyramid is for.
float multiscale_tex(float u, float v)
{
  float s = 0.f;
  s += 0.60f * std::sin(0.052f * u + 0.031f * v + 0.7f);
  s += 0.50f * std::sin(0.028f * u - 0.049f * v + 2.1f);
  s += 0.50f * std::sin(0.7854f * u + 1.1f);
  s += 0.45f * std::sin(0.7854f * v + 0.3f);
  return s;
}

Image multiscale_frame(int W, int H, float tx, float ty)
{
  Image img(W, H, 0);
  for(int y = 0; y < H; ++y)
    for(int x = 0; x < W; ++x)
    {
      const float v
          = std::clamp(128.f + 48.f * multiscale_tex(x - tx, y - ty), 0.f, 255.f);
      img.setGray(x, y, static_cast<std::uint8_t>(std::lround(v)));
    }
  return img;
}

// The standard texture over the whole frame, but with the RIGHT half's amplitude scaled down
// to `ampRight` grey levels (the left half keeps the standard 85). Both halves carry the same
// pattern and translate together, so the ground-truth displacement is identical on both sides
// and the ONLY thing that differs between a left and a right point is local contrast --
// which is what the minimum eigenvalue measures.
//
// The amplitude seam sits at x = 64. With the default radius 7 (a 15x15 window) a point at
// x = 32 sees only [25, 39] and a point at x = 96 only [89, 103], so neither window straddles
// it; the seam only shows up in the coarse pyramid levels, which do not decide `status`.
Image contrastSplit(float tx, float ty, float ampRight)
{
  Image img(kW, kH, 0);
  for(int y = 0; y < kH; ++y)
    for(int x = 0; x < kW; ++x)
    {
      const float amp = (x < kW / 2) ? 85.f : ampRight;
      const float v = std::clamp(128.f + amp * tex(x - tx, y - ty), 0.f, 255.f);
      img.setGray(x, y, static_cast<std::uint8_t>(std::lround(v)));
    }
  return img;
}

// Track one point through a reference frame and one translated by (3, 2) on a contrast-split
// scene, at a given `Min eigenvalue`. Returns the resulting track.
cv::tracked_point trackSplit(float px, float py, float ampRight, float minEig)
{
  cv::PointTracker t;
  t.inputs.min_eig.value = minEig;
  t.set(0, px / kW, py / kH);
  Image a = contrastSplit(0.f, 0.f, ampRight);
  feed(t.inputs.image, a);
  t();
  Image b = contrastSplit(3.f, 2.f, ampRight);
  feed(t.inputs.image, b);
  t();
  return t.outputs.points.value[0];
}

// The `Min eigenvalue` at which a point flips from tracked to lost, i.e. the eigenvalue the
// object actually reports for that window. `status` is monotone in the threshold (the
// eigenvalue itself does not depend on it), so bisection recovers it exactly.
float reportedMinEig(float px, float py, float ampRight)
{
  float lo = 0.f, hi = 1.f; // 1.0 is far above anything an 8-bit image can produce
  for(int i = 0; i < 30; ++i) // -> resolution 1e-9, four decades below the smallest value used
  {
    const float mid = 0.5f * (lo + hi);
    if(trackSplit(px, py, ampRight, mid).status == 1)
      lo = mid;
    else
      hi = mid;
  }
  return 0.5f * (lo + hi);
}

// Normalised <-> pixel helpers (the ports are normalised, cv.jit is in pixels).
float nx(float px, int W = kW)
{
  return px / static_cast<float>(W);
}
float ny(float py, int H = kH)
{
  return py / static_cast<float>(H);
}
float px_of(const cv::tracked_point& p, int W = kW)
{
  return p.x * static_cast<float>(W);
}
float py_of(const cv::tracked_point& p, int H = kH)
{
  return p.y * static_cast<float>(H);
}

// Two isolated 12x12 squares of different contrast on black (see the header comment).
// Strong square corners: (8,8) (19,8) (8,19) (19,19); weak: (44,44) .. (55,55).
Image twoSquares()
{
  Image img(64, 64, 0);
  img.fillRect(8, 8, 12, 12, 200);
  img.fillRect(44, 44, 12, 12, 126);
  return img;
}

// Area-coverage antialiased square over [ox, ox+24) x [oy, oy+24) continuous coordinates.
Image subpixelCorner(float ox, float oy)
{
  Image img(64, 64, 0);
  auto cov = [](float c, float lo, float hi) {
    const float a = std::max(c - 0.5f, lo);
    const float b = std::min(c + 0.5f, hi);
    return std::max(0.f, b - a);
  };
  for(int y = 0; y < 64; ++y)
    for(int x = 0; x < 64; ++x)
    {
      const float v = 255.f * cov(static_cast<float>(x), ox, ox + 24.f)
                      * cov(static_cast<float>(y), oy, oy + 24.f);
      img.setGray(x, y, static_cast<std::uint8_t>(std::lround(std::clamp(v, 0.f, 255.f))));
    }
  return img;
}
}

// ------------------------------------------------------------------------- PointTracker

TEST_CASE("PointTracker: the first frame produces no motion", "[pointtracker]")
{
  cv::PointTracker t;
  t.set(0, nx(60.f), ny(60.f));

  Image f0 = frame(0.f, 0.f);
  feed(t.inputs.image, f0);
  t();

  REQUIRE(t.outputs.points.value.size() == 1);
  CHECK(t.outputs.count.value == 1);
  const auto& p = t.outputs.points.value[0];
  // The seed is reported verbatim: there is no reference frame yet, so no displacement can
  // exist. (cv.jit.track instead swaps in its uninitialised buffer here and loses the seed.)
  CHECK(p.x == nx(60.f));
  CHECK(p.y == ny(60.f));
  CHECK(p.status == 1);
  CHECK(p.error == 0.f);
}

TEST_CASE(
    "PointTracker accumulates position across frames instead of reporting per-frame flow",
    "[pointtracker]")
{
  cv::PointTracker t;
  t.set(0, nx(60.f), ny(60.f));

  // Frame 0 is the reference; frames 1..5 translate by (3,2) px each.
  for(int k = 0; k <= 5; ++k)
  {
    Image img = frame(3.f * k, 2.f * k);
    feed(t.inputs.image, img);
    t();

    const auto& p = t.outputs.points.value[0];
    INFO("frame " << k);
    CHECK(p.status == 1);
    // Ground truth: seed + total translation so far.
    CHECK(px_of(p) == Approx(60.f + 3.f * k).margin(0.05));
    CHECK(py_of(p) == Approx(60.f + 2.f * k).margin(0.05));
  }

  // The load-bearing assertion: the TOTAL displacement after 5 frames is (15, 10), not the
  // single-frame (3, 2) that an instantaneous-flow object (cv::OpticalFlowLK) would report.
  const auto& p = t.outputs.points.value[0];
  CHECK(px_of(p) - 60.f == Approx(15.f).margin(0.05));
  CHECK(py_of(p) - 60.f == Approx(10.f).margin(0.05));
  CHECK(px_of(p) - 60.f > 4.f); // and unambiguously more than one frame's worth
}

TEST_CASE("PointTracker keeps positional identity: index i is always the same track",
          "[pointtracker]")
{
  cv::PointTracker t;
  const float sx[3] = {32.f, 86.f, 60.f};
  const float sy[3] = {32.f, 40.f, 96.f};
  for(int i = 0; i < 3; ++i)
    t.set(i, nx(sx[i]), ny(sy[i]));

  for(int k = 0; k <= 4; ++k)
  {
    Image img = frame(3.f * k, 2.f * k);
    feed(t.inputs.image, img);
    t();

    REQUIRE(t.outputs.points.value.size() == 3);
    for(int i = 0; i < 3; ++i)
    {
      INFO("frame " << k << " point " << i);
      const auto& p = t.outputs.points.value[static_cast<std::size_t>(i)];
      CHECK(p.status == 1);
      // Each index stays on ITS OWN seed's trajectory: the three tracks never swap, and
      // their relative geometry is preserved because the scene motion is a pure translation.
      CHECK(px_of(p) == Approx(sx[i] + 3.f * k).margin(0.05));
      CHECK(py_of(p) == Approx(sy[i] + 2.f * k).margin(0.05));
    }
  }
}

TEST_CASE("PointTracker: `set` reseeds one index without disturbing the others",
          "[pointtracker]")
{
  cv::PointTracker t;
  const float sx[3] = {32.f, 86.f, 60.f};
  const float sy[3] = {32.f, 40.f, 96.f};
  for(int i = 0; i < 3; ++i)
    t.set(i, nx(sx[i]), ny(sy[i]));

  for(int k = 0; k <= 3; ++k)
  {
    Image img = frame(3.f * k, 2.f * k);
    feed(t.inputs.image, img);
    t();
  }
  // After frame 3 every track has accumulated (9, 6).
  CHECK(px_of(t.outputs.points.value[1]) == Approx(86.f + 9.f).margin(0.05));

  // Re-seed only index 1, at a completely different place.
  t.set(1, nx(100.f), ny(100.f));

  Image img = frame(12.f, 8.f); // one more frame: the scene moved another (3, 2)
  feed(t.inputs.image, img);
  t();

  // Index 1 restarts from the new seed and moves by exactly one frame's translation...
  CHECK(px_of(t.outputs.points.value[1]) == Approx(103.f).margin(0.05));
  CHECK(py_of(t.outputs.points.value[1]) == Approx(102.f).margin(0.05));
  // ...while 0 and 2 keep their own accumulated trajectories, undisturbed.
  CHECK(px_of(t.outputs.points.value[0]) == Approx(32.f + 12.f).margin(0.05));
  CHECK(py_of(t.outputs.points.value[0]) == Approx(32.f + 8.f).margin(0.05));
  CHECK(px_of(t.outputs.points.value[2]) == Approx(60.f + 12.f).margin(0.05));
  CHECK(py_of(t.outputs.points.value[2]) == Approx(96.f + 8.f).margin(0.05));
}

TEST_CASE("PointTracker: a point leaving the frame reports status 0 and KEEPS its last "
          "coordinates",
          "[pointtracker]")
{
  cv::PointTracker t;
  t.set(0, nx(122.f), ny(60.f));

  Image f0 = frame(0.f, 0.f);
  feed(t.inputs.image, f0);
  t();
  const float lastX = t.outputs.points.value[0].x;
  const float lastY = t.outputs.points.value[0].y;
  REQUIRE(t.outputs.points.value[0].status == 1);

  // +6 px per frame from x = 122 in a 128-wide image: the point runs off the right edge.
  for(int k = 1; k <= 3; ++k)
  {
    Image img = frame(6.f * k, 0.f);
    feed(t.inputs.image, img);
    t();

    INFO("frame " << k);
    const auto& p = t.outputs.points.value[0];
    CHECK(p.status == 0);
    CHECK(p.error == 0.f); // as OpenCV does for an out-of-bounds point
    // Documented cv.jit behaviour, and the reason the tests exist: a lost point is NOT
    // deleted and NOT zeroed -- it keeps its last coordinates bit-for-bit, which are also
    // the starting guess it is retried from on the following frame.
    CHECK(p.x == lastX);
    CHECK(p.y == lastY);
  }
}

TEST_CASE("PointTracker: the pyramid tracks motion larger than the window",
          "[pointtracker]")
{
  // 24 px of motion with the default radius 7, i.e. a 15x15 window: the two windows barely
  // overlap, so this is only solvable coarse-to-fine.
  auto run = [](int max_level) {
    cv::PointTracker t;
    t.inputs.max_level.value = max_level;
    t.set(0, 90.f / 192.f, 96.f / 192.f);

    Image a = multiscale_frame(192, 192, 0.f, 0.f);
    feed(t.inputs.image, a);
    t();
    Image b = multiscale_frame(192, 192, 24.f, 0.f);
    feed(t.inputs.image, b);
    t();
    return t.outputs.points.value[0];
  };

  const auto withPyramid = run(3); // the OpenCV / cv.jit default maxLevel
  CHECK(withPyramid.status == 1);
  CHECK(px_of(withPyramid, 192) == Approx(114.f).margin(0.05));
  CHECK(py_of(withPyramid, 192) == Approx(96.f).margin(0.05));

  // Same data, single level: the fine grating that dominates the full-resolution gradient
  // traps the solve within a couple of pixels of the start. This is what the pyramid buys.
  const auto flat = run(0);
  CHECK(std::abs(px_of(flat, 192) - 90.f) < 2.f);
  CHECK(std::abs(px_of(flat, 192) - 114.f) > 20.f);
}

TEST_CASE("PointTracker fills in a per-point error", "[pointtracker]")
{
  // (a) A clean translation is matched almost exactly: the residual is at quantisation
  // level, several orders of magnitude below one grey level (1/255 = 0.0039).
  float cleanError = -1.f;
  {
    cv::PointTracker t;
    t.set(0, nx(60.f), ny(60.f));
    Image a = frame(0.f, 0.f);
    feed(t.inputs.image, a);
    t();
    Image b = frame(3.f, 0.f);
    feed(t.inputs.image, b);
    t();
    const auto& p = t.outputs.points.value[0];
    REQUIRE(p.status == 1);
    cleanError = p.error;
    CHECK(cleanError >= 0.f);
    CHECK(cleanError < 1.e-3f);
  }

  // (b) Same translation, but the second frame carries a +-20/255 two-pixel-period
  // modulation the tracker cannot absorb into a displacement. The residual is then the
  // modulation itself: mean |+-20/255| = 0.0784, slightly attenuated because the solve
  // settles a fraction of a pixel off the integer grid and bilinear sampling of a
  // two-pixel-period signal at a fractional offset averages it down.
  {
    cv::PointTracker t;
    t.set(0, nx(60.f), ny(60.f));
    Image a = frame(0.f, 0.f);
    feed(t.inputs.image, a);
    t();
    Image b = frame(3.f, 0.f, 20);
    feed(t.inputs.image, b);
    t();
    const auto& p = t.outputs.points.value[0];
    REQUIRE(p.status == 1);
    CHECK(p.error == Approx(0.0784f).margin(0.02));
    CHECK(p.error > 50.f * cleanError);
  }
}

TEST_CASE("PointTracker: the seed list sizes the track set and only re-seeds when it changes",
          "[pointtracker]")
{
  cv::PointTracker t;
  t.inputs.seeds.value = {{nx(40.f), ny(40.f), 1.f}, {nx(80.f), ny(70.f), 1.f}};

  Image f0 = frame(0.f, 0.f);
  feed(t.inputs.image, f0);
  t();
  REQUIRE(t.outputs.points.value.size() == 2); // the list size wins over the `Points` control
  CHECK(t.outputs.count.value == 2);
  CHECK(px_of(t.outputs.points.value[0]) == Approx(40.f).margin(1e-4));

  // The list is left UNCHANGED across the following frames, so the tracks must keep
  // running. (Re-applying the seeds every frame would pin both points to their seeds --
  // that is the failure mode this test exists to catch.)
  for(int k = 1; k <= 3; ++k)
  {
    Image img = frame(3.f * k, 2.f * k);
    feed(t.inputs.image, img);
    t();
  }
  CHECK(px_of(t.outputs.points.value[0]) == Approx(49.f).margin(0.05));
  CHECK(py_of(t.outputs.points.value[0]) == Approx(46.f).margin(0.05));
  CHECK(px_of(t.outputs.points.value[1]) == Approx(89.f).margin(0.05));

  // Changing the list re-seeds everything, and resizes the track set.
  t.inputs.seeds.value = {{nx(20.f), ny(20.f), 1.f}};
  Image f4 = frame(12.f, 8.f);
  feed(t.inputs.image, f4);
  t();
  REQUIRE(t.outputs.points.value.size() == 1);
  // Re-seeded at (20,20) on the previous frame's reference, then moved by one frame's (3,2).
  CHECK(px_of(t.outputs.points.value[0]) == Approx(23.f).margin(0.05));
  CHECK(py_of(t.outputs.points.value[0]) == Approx(22.f).margin(0.05));
}

TEST_CASE("PointTracker: `reset` drops the tracks and the reference frame", "[pointtracker]")
{
  cv::PointTracker t;
  t.set(0, nx(60.f), ny(60.f));
  for(int k = 0; k <= 2; ++k)
  {
    Image img = frame(3.f * k, 2.f * k);
    feed(t.inputs.image, img);
    t();
  }
  REQUIRE(px_of(t.outputs.points.value[0]) == Approx(66.f).margin(0.05));

  t.reset();
  CHECK(t.outputs.points.value.empty());
  CHECK(t.outputs.count.value == 0);

  // After a reset the object is back to its default single track at the origin, and the
  // next frame becomes the new reference (no motion reported).
  t.set(0, nx(50.f), ny(50.f));
  Image img = frame(9.f, 6.f);
  feed(t.inputs.image, img);
  t();
  REQUIRE(t.outputs.points.value.size() == 1);
  CHECK(t.outputs.points.value[0].x == nx(50.f));
  CHECK(t.outputs.points.value[0].y == ny(50.f));
}

TEST_CASE("PointTracker: `Points` sizes the track set when no seed list is connected",
          "[pointtracker]")
{
  cv::PointTracker t;
  t.inputs.npoints.value = 4;
  Image f0 = frame(0.f, 0.f);
  feed(t.inputs.image, f0);
  t();
  REQUIRE(t.outputs.points.value.size() == 4);
  // Unseeded tracks start at the origin (as cv.jit's default-constructed Point2f do).
  CHECK(t.outputs.points.value[3].x == 0.f);
  CHECK(t.outputs.points.value[3].y == 0.f);

  // `set` beyond the control's count grows the set rather than erroring out.
  t.set(9, nx(60.f), ny(60.f));
  feed(t.inputs.image, f0);
  t();
  REQUIRE(t.outputs.points.value.size() == 10);
  CHECK(t.outputs.points.value[9].x == nx(60.f));
}

TEST_CASE("PointTracker survives degenerate and changing inputs", "[pointtracker]")
{
  cv::PointTracker t;
  t.set(0, nx(60.f), ny(60.f));

  SECTION("no texture at all: nothing to track, position is kept")
  {
    Image a(kW, kH, 100);
    feed(t.inputs.image, a);
    t();
    Image b(kW, kH, 100);
    feed(t.inputs.image, b);
    t();
    REQUIRE(t.outputs.points.value.size() == 1);
    CHECK(t.outputs.points.value[0].status == 0);
    CHECK(t.outputs.points.value[0].x == nx(60.f));
  }

  SECTION("dimension change mid-stream restarts from a new reference frame")
  {
    Image a = frame(0.f, 0.f);
    feed(t.inputs.image, a);
    t();
    Image small = frame(3.f, 2.f, 0, 40, 40);
    feed(t.inputs.image, small);
    t();
    REQUIRE(t.outputs.points.value.size() == 1);
    CHECK(t.outputs.points.value[0].x == nx(60.f)); // no motion: new reference
    Image small2 = frame(6.f, 4.f, 0, 40, 40);
    feed(t.inputs.image, small2);
    t();
    CHECK(std::isfinite(t.outputs.points.value[0].x));
  }

  SECTION("a 1x1 frame is ignored")
  {
    Image tiny(1, 1, 200);
    feed(t.inputs.image, tiny);
    t();
    CHECK(t.outputs.points.value.size() <= 1);
  }

  SECTION("an unchanged texture is a no-op")
  {
    Image a = frame(0.f, 0.f);
    feed(t.inputs.image, a);
    t();
    t.inputs.image.texture.changed = false;
    t.outputs.count = -1;
    t();
    CHECK(t.outputs.count.value == -1);
  }
}

// -------------------------------------------------------------- Min eigenvalue (calibration)
//
// WHY THESE TESTS EXIST, AND WHAT THEY PIN
//
// OpenCV's `minEigThreshold` is applied to the minimum eigenvalue of the windowed structure
// tensor, divided by the window area. OpenCV builds that tensor from SCHARR derivatives of
// 8-BIT grey and then RESCALES it by FLT_SCALE = 1/(1<<20) before the test
// (modules/video/src/lkpyramid.cpp); this object builds it from central differences of [0,1]
// grey. Scharr on 8-bit returns 32 * 255 * (the [0,1] central difference) for a locally linear
// patch, and the eigenvalue is quadratic in the gradient, so the conversion factor is
//
//     (32 * 255)^2 / 2^20 = 66585600 / 1048576 = 63.5009765625
//
// The code used to apply (32*255)^2 with no FLT_SCALE, i.e. 2^20 = 1048576 times too much.
// The "Min eigenvalue" control has range [0, 0.01]; with the inflated factor the reported
// eigenvalue of a well-textured 15x15 window was ~6.4e3, so NO setting of the control could
// ever reject anything, and the only rejection that ever fired was the separate determinant
// guard (a completely flat window). Measured, on the scene below, before and after:
//
//     right-half amplitude   85     40     20     10      6      0(flat)
//     reported minEig, old   6.4e3  1.4e3  3.8e2  1.3e2  7.7e1   ~4e-22
//     reported minEig, new   6.1e-3 1.4e-3 3.6e-4 1.3e-4 7.3e-5  ~4e-22
//     (ratio: 2^20 = 1048576 throughout)
//
// so at the OpenCV default of 1e-4 the amplitude-6 window -- a window with barely more
// contrast than 8-bit quantisation noise, which OpenCV and cv.jit both reject -- used to be
// reported as successfully tracked. It is now correctly reported LOST.
TEST_CASE("PointTracker: the Min eigenvalue control's whole range is live", "[pointtracker]")
{
  cv::PointTracker probe;
  // The port's declared range is [0, 0.01] with the OpenCV default 1e-4 as initial value.
  REQUIRE(probe.inputs.min_eig.value == 0.0001f);
  constexpr float kPortMax = 0.01f;

  // A well-textured point on the full-amplitude scene.
  CHECK(trackSplit(96.f, 64.f, 85.f, 0.f).status == 1);
  CHECK(trackSplit(96.f, 64.f, 85.f, 1e-4f).status == 1);
  CHECK(trackSplit(96.f, 64.f, 85.f, 1e-3f).status == 1);
  // ...and it IS rejected at the top of the control's range. This single assertion is what
  // fails by a factor of 2^20 without the FLT_SCALE division: the old code reported ~6.4e3
  // for this window, so no value the user can dial in ever fired.
  CHECK(trackSplit(96.f, 64.f, 85.f, kPortMax).status == 0);

  const float e = reportedMinEig(96.f, 64.f, 85.f);
  INFO("reported minEig = " << e);
  CHECK(e > 1e-3f);
  CHECK(e < kPortMax);
  // ~63.5 x the raw [0,1]-grey eigenvalue; anything near 6e3 means the 2^20 is missing again.
  CHECK(e < 1.f);
}

TEST_CASE("PointTracker: the reported eigenvalue is quadratic in contrast", "[pointtracker]")
{
  // Halving the contrast of a window quarters the minimum eigenvalue, because the structure
  // tensor is built from products of gradients. Same point, same pattern, same displacement --
  // only the amplitude changes -- so the ratio is a property of the units alone.
  const float e85 = reportedMinEig(96.f, 64.f, 85.f);
  const float e40 = reportedMinEig(96.f, 64.f, 40.f);
  INFO("minEig(85) = " << e85 << ", minEig(40) = " << e40);
  CHECK(e85 > e40);
  // (40/85)^2 = 0.22145. The measured ratio is a few percent high because 8-bit quantisation
  // adds a contrast-independent gradient floor that matters relatively more at amplitude 40.
  CHECK(e40 / e85 == Approx(0.22145f).epsilon(0.12));
  // Both land inside the control's [0, 0.01] range, which is the whole point of the
  // calibration: the control can express thresholds that discriminate between them.
  CHECK(e40 < 0.01f);
  CHECK(e85 < 0.01f);
  CHECK(e40 > 1e-4f);
}

TEST_CASE("PointTracker: min_eig rejects low-contrast windows and keeps textured ones",
          "[pointtracker]")
{
  // Left point (32, 64) is always on the amplitude-85 half; right point (96, 64) is on the
  // half whose amplitude the test varies. Ground truth for both is +(3, 2) px.
  SECTION("with the gate open, both are tracked to the same ground truth")
  {
    const auto strong = trackSplit(32.f, 64.f, 20.f, 0.f);
    const auto weak = trackSplit(96.f, 64.f, 20.f, 0.f);
    CHECK(strong.status == 1);
    CHECK(weak.status == 1);
    CHECK(px_of(strong) == Approx(35.f).margin(0.05));
    CHECK(py_of(strong) == Approx(66.f).margin(0.05));
    CHECK(px_of(weak) == Approx(99.f).margin(0.05));
    CHECK(py_of(weak) == Approx(66.f).margin(0.05));
  }

  SECTION("a threshold between the two contrasts keeps one and drops the other")
  {
    // minEig is ~6.1e-3 at amplitude 85 and ~3.6e-4 at amplitude 20; 1e-3 sits between them.
    const float thr = 1e-3f;
    CHECK(trackSplit(32.f, 64.f, 20.f, thr).status == 1); // strong survives
    const auto weak = trackSplit(96.f, 64.f, 20.f, thr);
    CHECK(weak.status == 0);        // weak rejected
    CHECK(weak.error == 0.f);       // as OpenCV does for a rejected point
    CHECK(px_of(weak) == Approx(96.f).margin(1e-4)); // and it keeps its last coordinates
  }

  SECTION("the OpenCV default of 1e-4 behaves sanely on both")
  {
    // 1e-4 is meant to reject only windows with essentially no texture. Amplitude 20 is
    // low-contrast but real (minEig 3.6e-4) and must survive; amplitude 6 is barely above
    // quantisation noise (minEig 7.3e-5) and must not.
    const float def = 1e-4f;
    CHECK(trackSplit(96.f, 64.f, 85.f, def).status == 1);
    CHECK(trackSplit(96.f, 64.f, 20.f, def).status == 1);
    CHECK(px_of(trackSplit(96.f, 64.f, 20.f, def)) == Approx(99.f).margin(0.05));

    const auto tooWeak = trackSplit(96.f, 64.f, 6.f, def);
    CHECK(tooWeak.status == 0);
    // THE REGRESSION: with the 2^20-inflated factor this window reported minEig 77, sailed
    // through the gate and was published as status = 1.
    CHECK(px_of(tooWeak) == Approx(96.f).margin(1e-4));
    // The left half of the very same frame is unaffected.
    CHECK(trackSplit(32.f, 64.f, 6.f, def).status == 1);
  }

  SECTION("a flat window is rejected even with the gate fully open")
  {
    // Nothing to do with the eigenvalue: this is the determinant guard, and it is the only
    // rejection the object could perform before the calibration was fixed.
    CHECK(trackSplit(96.f, 64.f, 0.f, 0.f).status == 0);
    CHECK(trackSplit(32.f, 64.f, 0.f, 0.f).status == 1); // ...and only where it applies
  }
}

// --------------------------------------------------------- Max iterations / Epsilon (LK)
//
// Both control the same loop: at each pyramid level the Newton step is repeated at most
// `Max iterations` times, stopping early once the last update is <= `Epsilon` pixels. The
// scene is a pure 6 px translation tracked SINGLE-LEVEL (Max level 0), so the loop has to do
// all the work itself and the successive iterates are visible. Measured iterates of the x
// displacement (truth 6.0):
//
//     iteration      1        2        3        4       5+
//     estimate    4.3235   5.8997   5.9955   5.9998   6.0000
//     |update|    4.341    1.614    0.106    0.0048   < 1e-4
//
// which is ordinary quadratic Newton convergence. Everything below is read off that table.
TEST_CASE("PointTracker: `Max iterations` bounds the LK refinement", "[pointtracker]")
{
  auto run = [](int maxIter, float eps) {
    cv::PointTracker t;
    t.inputs.max_level.value = 0; // single level: the iteration count is the only lever
    t.inputs.max_iter.value = maxIter;
    t.inputs.epsilon.value = eps;
    t.set(0, nx(60.f), ny(60.f));
    Image a = frame(0.f, 0.f);
    feed(t.inputs.image, a);
    t();
    Image b = frame(6.f, 0.f);
    feed(t.inputs.image, b);
    t();
    return t.outputs.points.value[0];
  };

  REQUIRE(cv::PointTracker{}.inputs.max_iter.value == 30); // OpenCV's effective default

  const auto i1 = run(1, 0.f);
  const auto i2 = run(2, 0.f);
  const auto i3 = run(3, 0.f);
  const auto i5 = run(5, 0.f);
  const auto i30 = run(30, 0.f);

  for(const auto* p : {&i1, &i2, &i3, &i5, &i30})
    CHECK(p->status == 1); // the window is well textured throughout: never lost

  // One Newton step from a zero guess only recovers ~72% of a 6 px displacement, because the
  // linearisation is taken at the un-warped position.
  CHECK(px_of(i1) - 60.f == Approx(4.3235f).margin(0.02));
  CHECK(px_of(i2) - 60.f == Approx(5.8997f).margin(0.02));
  CHECK(px_of(i3) - 60.f == Approx(5.9955f).margin(0.02));
  // By 5 iterations it has converged to the quantisation floor and more iterations change
  // nothing at all.
  CHECK(px_of(i5) - 60.f == Approx(6.f).margin(0.001));

  // Strictly monotone improvement -- this is what a bounded iteration count means.
  const auto err = [](const cv::tracked_point& p) { return std::abs(px_of(p) - 66.f); };
  CHECK(err(i1) > err(i2));
  CHECK(err(i2) > err(i3));
  CHECK(err(i3) > err(i5));
  CHECK(err(i1) > 1.5f);   // clearly unconverged
  CHECK(err(i5) < 0.001f); // clearly converged
  // Past convergence the extra 25 iterations move the estimate by less than 1e-4 px: they
  // are chasing the float noise floor of the bilinear resampling, nothing more.
  CHECK(std::abs(px_of(i30) - px_of(i5)) < 1e-4f);
  CHECK(std::abs(py_of(i30) - py_of(i5)) < 1e-4f);
}

TEST_CASE("PointTracker: `Epsilon` stops the LK refinement early", "[pointtracker]")
{
  auto run = [](int maxIter, float eps) {
    cv::PointTracker t;
    t.inputs.max_level.value = 0;
    t.inputs.max_iter.value = maxIter;
    t.inputs.epsilon.value = eps;
    t.set(0, nx(60.f), ny(60.f));
    Image a = frame(0.f, 0.f);
    feed(t.inputs.image, a);
    t();
    Image b = frame(6.f, 0.f);
    feed(t.inputs.image, b);
    t();
    return t.outputs.points.value[0];
  };

  REQUIRE(cv::PointTracker{}.inputs.epsilon.value == 0.01f); // the OpenCV / cv.jit default

  // The updates are 4.341, 1.614, 0.106, 0.0048, ... pixels. `Epsilon` stops AFTER the first
  // update that is <= epsilon, so an iteration budget of 30 with epsilon = 2 must produce
  // EXACTLY the two-iteration answer (4.341 > 2, then 1.614 <= 2 -> stop) and epsilon = 1
  // exactly the three-iteration answer (1.614 > 1, then 0.106 <= 1 -> stop). Same arithmetic,
  // same number of updates, so the results are bit-identical -- not merely close.
  CHECK(run(30, 2.0f).x == run(2, 0.f).x);
  CHECK(run(30, 2.0f).y == run(2, 0.f).y);
  CHECK(run(30, 1.0f).x == run(3, 0.f).x);
  CHECK(run(30, 1.0f).y == run(3, 0.f).y);

  // A coarser epsilon is therefore strictly less accurate, and epsilon = 0 (never satisfied)
  // spends the whole budget and lands on the truth.
  const auto err = [](const cv::tracked_point& p) { return std::abs(px_of(p) - 66.f); };
  CHECK(err(run(30, 2.0f)) > err(run(30, 1.0f)));
  CHECK(err(run(30, 1.0f)) > err(run(30, 0.1f)));
  CHECK(err(run(30, 0.1f)) > err(run(30, 0.f)));
  CHECK(err(run(30, 0.f)) < 0.001f);
  // The default epsilon of 0.01 px is far below the first three updates, so it costs nothing:
  // it converges to the same answer as no epsilon at all.
  CHECK(err(run(30, 0.01f)) < 0.001f);
}

// ------------------------------------------------------------------------- GoodFeatures

TEST_CASE("GoodFeatures sorts strongest first and cuts on a RELATIVE quality level",
          "[goodfeatures]")
{
  Image img = twoSquares();
  cv::GoodFeatures gf;
  gf.inputs.distance.value = 5.f; // the cv.jit default; the squares' corners are 11 px apart

  SECTION("quality 0.3 keeps both squares")
  {
    gf.inputs.quality.value = 0.3f;
    feed(gf.inputs.image, img);
    gf();

    const auto& f = gf.outputs.features.value;
    REQUIRE(f.size() == 8); // 4 corners per square
    CHECK(gf.outputs.count.value == 8);

    // Sorted strongest first.
    for(std::size_t i = 1; i < f.size(); ++i)
      CHECK(f[i - 1].score >= f[i].score);

    // The first four are the strong square's corners, the last four the weak square's.
    for(int i = 0; i < 4; ++i)
    {
      CHECK(f[static_cast<std::size_t>(i)].x * 64 < 32.f);
      CHECK(f[static_cast<std::size_t>(i) + 4].x * 64 > 32.f);
    }

    // Shi-Tomasi is quadratic in contrast: (126/200)^2 = 0.3969 exactly.
    CHECK(f[4].score / f[0].score == Approx(0.3969f).epsilon(0.01));
  }

  SECTION("quality 0.5 cuts the 40%-strength corners")
  {
    gf.inputs.quality.value = 0.5f;
    feed(gf.inputs.image, img);
    gf();

    const auto& f = gf.outputs.features.value;
    REQUIRE(f.size() == 4);
    for(const auto& p : f)
      CHECK(p.x * 64 < 32.f); // only the strong square survived
  }

  SECTION("quality 1.0 keeps the strongest corners")
  {
    // Deliberate deviation, and the reason this case is pinned: OpenCV thresholds with a
    // strict `>`, so qualityLevel = 1 returns NOTHING (the maximum is not greater than
    // itself). Ours is `>=`, so the control means what it says.
    gf.inputs.quality.value = 1.f;
    feed(gf.inputs.image, img);
    gf();
    const auto& f = gf.outputs.features.value;
    REQUIRE(!f.empty()); // OpenCV's strict `>` would give an empty list here
    // Only the maximum itself (the four corners are equal to within a float ulp, so how
    // many tie exactly is not something to assert on) and it belongs to the strong square.
    CHECK(f.size() <= 4);
    for(const auto& p : f)
      CHECK(p.x * 64 < 32.f);
  }
}

TEST_CASE("GoodFeatures: minDistance de-clusters greedily, strongest first",
          "[goodfeatures]")
{
  Image img = twoSquares();
  cv::GoodFeatures gf;
  gf.inputs.quality.value = 0.3f;
  gf.inputs.distance.value = 20.f; // > the 11 px between a square's own corners
  feed(gf.inputs.image, img);
  gf();

  const auto& f = gf.outputs.features.value;
  // One survivor per square: taking a square's strongest corner suppresses its three
  // siblings (11 px away), while the other square is 25*sqrt(2) = 35 px away and survives.
  REQUIRE(f.size() == 2);
  CHECK(f[0].score > f[1].score); // the strong square's corner is kept first

  const float dx = (f[0].x - f[1].x) * 64.f;
  const float dy = (f[0].y - f[1].y) * 64.f;
  CHECK(std::sqrt(dx * dx + dy * dy) >= 20.f);

  SECTION("all pairwise distances respect the spacing on a denser setting")
  {
    gf.inputs.distance.value = 8.f;
    feed(gf.inputs.image, img);
    gf();
    const auto& g = gf.outputs.features.value;
    REQUIRE(g.size() == 8);
    for(std::size_t i = 0; i < g.size(); ++i)
      for(std::size_t j = i + 1; j < g.size(); ++j)
      {
        const float ax = (g[i].x - g[j].x) * 64.f;
        const float ay = (g[i].y - g[j].y) * 64.f;
        CHECK(std::sqrt(ax * ax + ay * ay) >= 8.f);
      }
  }
}

TEST_CASE("GoodFeatures: the ROI restricts detection", "[goodfeatures]")
{
  Image img = twoSquares();
  cv::GoodFeatures gf;
  gf.inputs.quality.value = 0.3f;
  gf.inputs.distance.value = 5.f;
  gf.inputs.useroi.value = true;

  SECTION("corners outside the ROI are excluded")
  {
    gf.inputs.roi_x1.value = 0;
    gf.inputs.roi_y1.value = 0;
    gf.inputs.roi_x2.value = 30;
    gf.inputs.roi_y2.value = 30;
    feed(gf.inputs.image, img);
    gf();

    REQUIRE(gf.outputs.features.value.size() == 4);
    for(const auto& p : gf.outputs.features.value)
    {
      CHECK(p.x * 64 <= 30.f);
      CHECK(p.y * 64 <= 30.f);
    }
  }

  SECTION("the quality level is relative to the strongest corner INSIDE the ROI")
  {
    // ROI over the weak square only. Its corners are at 39.7% of the global maximum, so a
    // global reference would drop them all at quality 0.9; because the reference maximum is
    // taken inside the mask (as OpenCV's minMaxLoc with a mask does), they all survive.
    gf.inputs.quality.value = 0.9f;
    gf.inputs.roi_x1.value = 40;
    gf.inputs.roi_y1.value = 40;
    gf.inputs.roi_x2.value = 60;
    gf.inputs.roi_y2.value = 60;
    feed(gf.inputs.image, img);
    gf();

    REQUIRE(gf.outputs.features.value.size() == 4);
    for(const auto& p : gf.outputs.features.value)
      CHECK(p.x * 64 > 32.f);
  }

  SECTION("useroi off ignores the ROI values entirely")
  {
    gf.inputs.useroi.value = false;
    gf.inputs.roi_x1.value = 0;
    gf.inputs.roi_y1.value = 0;
    gf.inputs.roi_x2.value = 30;
    gf.inputs.roi_y2.value = 30;
    feed(gf.inputs.image, img);
    gf();
    CHECK(gf.outputs.features.value.size() == 8);
  }
}

TEST_CASE("GoodFeatures: sub-pixel refinement lands off-grid and closer to the true corner",
          "[goodfeatures]")
{
  // The square's true top-left corner is at (20.3, 20.3).
  Image img = subpixelCorner(20.3f, 20.3f);
  constexpr float kTrue = 20.3f;

  auto detect = [&](bool precision) {
    cv::GoodFeatures gf;
    gf.inputs.quality.value = 0.3f;
    gf.inputs.distance.value = 10.f;
    gf.inputs.precision.value = precision;
    feed(gf.inputs.image, img);
    gf();
    REQUIRE(!gf.outputs.features.value.empty());
    return gf.outputs.features.value[0]; // strongest = the top-left corner
  };

  const auto raw = detect(false);
  const auto fine = detect(true);

  const float rawX = raw.x * 64.f;
  const float fineX = fine.x * 64.f;

  // Without refinement the answer is an integer pixel index, by construction.
  CHECK(rawX == Approx(std::round(rawX)).margin(1e-4));
  // With refinement it is not.
  CHECK(std::abs(fineX - std::round(fineX)) > 0.05f);
  // And it is strictly closer to the true corner.
  CHECK(std::abs(fineX - kTrue) < std::abs(rawX - kTrue));
  CHECK(std::abs(fineX - kTrue) < 0.25f);
  CHECK(std::abs(fine.y * 64.f - kTrue) < 0.25f);
}

TEST_CASE("GoodFeatures: degenerate inputs", "[goodfeatures]")
{
  cv::GoodFeatures gf;

  SECTION("a flat image yields nothing")
  {
    Image img(32, 32, 137);
    feed(gf.inputs.image, img);
    gf();
    CHECK(gf.outputs.features.value.empty());
    CHECK(gf.outputs.count.value == 0);
  }

  SECTION("a fully black image yields nothing")
  {
    Image img(32, 32, 0);
    feed(gf.inputs.image, img);
    gf();
    CHECK(gf.outputs.features.value.empty());
  }

  SECTION("an image too small for the operators is ignored")
  {
    Image img(3, 3, 0);
    img.setGray(1, 1, 255);
    feed(gf.inputs.image, img);
    gf();
    CHECK(gf.outputs.features.value.empty());
  }

  SECTION("Max features caps the output, keeping the strongest")
  {
    Image img = twoSquares();
    gf.inputs.quality.value = 0.3f;
    gf.inputs.distance.value = 5.f;
    gf.inputs.max_features.value = 3;
    feed(gf.inputs.image, img);
    gf();
    REQUIRE(gf.outputs.features.value.size() == 3);
    for(const auto& p : gf.outputs.features.value)
      CHECK(p.x * 64 < 32.f); // only the strong square's corners
  }

  SECTION("an empty ROI yields nothing")
  {
    Image img = twoSquares();
    gf.inputs.useroi.value = true;
    gf.inputs.roi_x1.value = 61;
    gf.inputs.roi_y1.value = 61;
    gf.inputs.roi_x2.value = 63;
    gf.inputs.roi_y2.value = 63;
    feed(gf.inputs.image, img);
    gf();
    CHECK(gf.outputs.features.value.empty());
  }
}

// -------------------------------------------------------------------------------- chain

TEST_CASE("GoodFeatures -> PointTracker chains directly (cv.jit.features2track)",
          "[pointtracker][goodfeatures][chain]")
{
  cv::GoodFeatures gf;
  cv::PointTracker t;

  // Detect on the reference frame, over a central ROI so no feature sits on the border.
  Image f0 = frame(0.f, 0.f);
  gf.inputs.quality.value = 0.5f;
  gf.inputs.distance.value = 15.f;
  gf.inputs.useroi.value = true;
  gf.inputs.roi_x1.value = 24;
  gf.inputs.roi_y1.value = 24;
  gf.inputs.roi_x2.value = 104;
  gf.inputs.roi_y2.value = 104;
  feed(gf.inputs.image, f0);
  gf();
  const auto seeds = gf.outputs.features.value;
  REQUIRE(seeds.size() >= 6);

  // No adapter: both ports carry std::vector<cv::feature_point>.
  t.inputs.seeds.value = seeds;

  for(int k = 0; k <= 4; ++k)
  {
    Image img = frame(2.f * k, 1.f * k);
    feed(t.inputs.image, img);
    t();
  }

  REQUIRE(t.outputs.points.value.size() == seeds.size());
  for(std::size_t i = 0; i < seeds.size(); ++i)
  {
    INFO("track " << i);
    const auto& p = t.outputs.points.value[i];
    CHECK(p.status == 1);
    // Total translation over the 4 frames after the reference: (8, 4) px.
    CHECK(px_of(p) == Approx(seeds[i].x * kW + 8.f).margin(0.1));
    CHECK(py_of(p) == Approx(seeds[i].y * kH + 4.f).margin(0.1));
  }
}
